import type { BasicConfig, ThemeConfig, PluginConfig, Language } from '../types/config';
import { PLUGINS, COLOR_SCHEME_PLUGINS } from '../config/plugins';

const COMMENTS = {
  en: {
    header: {
      separator: '" ===============================================',
      vimConfig: '" Vim Configuration',
      generatedBy: '" Generated by Vim Config UI',
    },
    basicSettings: {
      title: '" === Basic Settings ===',
      syntax: '" Enable syntax highlighting for code',
      nocompatible: '" Disable Vi compatibility (required for Vim features)',
      mouse: '" Enable mouse support (a=all, n=normal, v=visual, i=insert)',
      mouseOptions: '" Options: n,v,i,a (or empty to disable)',
      lineNumbers: '" --- Line Numbers ---',
      absoluteNumbers: '" Show absolute line numbers',
      relativeNumbers: '" Show relative line numbers (useful for motions like 3j)',
      cursorLine: '" Highlight the current line',
      noWrap: '" Disable line wrapping',
      indentation: '" --- Indentation ---',
      tabstop: '" Number of spaces that a <Tab> in the file counts for',
      shiftwidth: '" Number of spaces to use for each step of (auto)indent',
      expandtab: '" Use spaces instead of tabs',
      autoindent: '" Auto indent new lines',
      smartindent: '" Smart indent (recognizes C/C++ syntax)',
      search: '" --- Search ---',
      hlsearch: '" Highlight all search matches',
      incsearch: '" Show search matches as you type',
      ignorecase: '" Case-insensitive searching...',
      smartcase: '" ...unless the search pattern contains uppercase letters',
      ui: '" --- UI Enhancement ---',
      showcmd: '" Show command in status line (e.g., showing partial commands)',
      showmode: '" Show current mode (INSERT, VISUAL, etc.)',
      showmatch: '" Highlight matching bracket when cursor is on one',
      wildmenu: '" Enhanced command-line completion (shows list of matches)',
      files: '" --- File Handling ---',
      nobackup: '" Don\'t create backup files (~ suffix)',
      nowrite: '" Don\'t create backup files before overwriting',
      noswapfile: '" Don\'t use swap files (.swp)',
    },
    plugins: {
      title: '" === Plugins (vim-plug) ===',
      step1: '" Step 1: Install vim-plug (if not already installed)',
      step1Desc: '" Run this command in your terminal:',
      step2: '" Step 2: Install plugins',
      step2Desc: '" Open Vim and run: :PlugInstall',
      colorSchemes: '" --- Color Schemes ---',
      plugins: '" --- Plugins ---',
      customConfig: '" Custom config:',
    },
    theme: {
      title: '" === Theme Settings ===',
      colorScheme: '" Color scheme:',
      background: '" Background:',
    },
  },
  zh: {
    header: {
      separator: '" ===============================================',
      vimConfig: '" Vim 配置文件',
      generatedBy: '" 由 Vim Config UI 生成',
    },
    basicSettings: {
      title: '" === 基础设置 ===',
      syntax: '" 启用代码语法高亮',
      nocompatible: '" 禁用 Vi 兼容模式（启用 Vim 特性）',
      mouse: '" 启用鼠标支持 (a=全部, n=普通, v=可视, i=插入)',
      mouseOptions: '" 选项: n,v,i,a (或留空禁用)',
      lineNumbers: '" --- 行号设置 ---',
      absoluteNumbers: '" 显示绝对行号',
      relativeNumbers: '" 显示相对行号 (适用于 3j 等移动命令)',
      cursorLine: '" 高亮当前行',
      noWrap: '" 禁用自动换行',
      indentation: '" --- 缩进设置 ---',
      tabstop: '" Tab 键对应的空格数',
      shiftwidth: '" 每级缩进的空格数',
      expandtab: '" 使用空格代替 Tab',
      autoindent: '" 自动缩进新行',
      smartindent: '" 智能缩进 (识别 C/C++ 语法)',
      search: '" --- 搜索设置 ---',
      hlsearch: '" 高亮显示所有搜索结果',
      incsearch: '" 输入时即时显示搜索匹配',
      ignorecase: '" 忽略大小写搜索...',
      smartcase: '" ...除非搜索模式包含大写字母',
      ui: '" --- 界面增强 ---',
      showcmd: '" 在状态栏显示命令 (如显示部分输入的命令)',
      showmode: '" 显示当前模式 (插入、可视等)',
      showmatch: '" 光标在括号上时高亮匹配的括号',
      wildmenu: '" 增强的命令行补全 (显示匹配列表)',
      files: '" --- 文件处理 ---',
      nobackup: '" 不创建备份文件 (~ 后缀)',
      nowrite: '" 覆写文件前不创建备份',
      noswapfile: '" 不使用交换文件 (.swp)',
    },
    plugins: {
      title: '" === 插件 (vim-plug) ===',
      step1: '" 步骤 1: 安装 vim-plug (如果尚未安装)',
      step1Desc: '" 在终端中运行以下命令:',
      step2: '" 步骤 2: 安装插件',
      step2Desc: '" 打开 Vim 并运行: :PlugInstall',
      colorSchemes: '" --- 配色方案 ---',
      plugins: '" --- 插件 ---',
      customConfig: '" 自定义配置:',
    },
    theme: {
      title: '" === 主题设置 ===',
      colorScheme: '" 配色方案:',
      background: '" 背景:',
    },
  },
};

export function generateVimrc(
  basic: BasicConfig,
  theme: ThemeConfig,
  plugins: PluginConfig,
  lang: Language = 'en'
): string {
  const t = COMMENTS[lang];
  const lines: string[] = [
    t.header.separator,
    t.header.vimConfig,
    t.header.generatedBy,
    t.header.separator,
    ""
  ];

  // Basic Settings
  lines.push(t.header.separator);
  lines.push(t.basicSettings.title);
  lines.push(t.header.separator);
  lines.push("");

  if (basic.enable) {
    lines.push(t.basicSettings.syntax);
    lines.push("syntax enable");
    lines.push("");
  }

  if (basic.nocompatible) {
    lines.push(t.basicSettings.nocompatible);
    lines.push("set nocompatible");
    lines.push("");
  }

  if (basic.mouse) {
    lines.push(t.basicSettings.mouse);
    lines.push(`set mouse=${basic.mouse}  ${t.basicSettings.mouseOptions}`);
    lines.push("");
  }

  // Line Numbers
  if (basic.number || basic.relativenumber || basic.cursorline) {
    lines.push(t.basicSettings.lineNumbers);
    if (basic.number) {
      lines.push(t.basicSettings.absoluteNumbers);
      lines.push("set number");
    }
    if (basic.relativenumber) {
      lines.push(t.basicSettings.relativeNumbers);
      lines.push("set relativenumber");
    }
    if (basic.cursorline) {
      lines.push(t.basicSettings.cursorLine);
      lines.push("set cursorline");
    }
    lines.push("");
  }

  if (!basic.wrap) {
    lines.push(t.basicSettings.noWrap);
    lines.push("set nowrap");
    lines.push("");
  }

  // Indentation
  if (basic.tabstop || basic.shiftwidth || basic.expandtab || basic.autoindent || basic.smartindent) {
    lines.push(t.basicSettings.indentation);
    if (basic.tabstop) {
      lines.push(t.basicSettings.tabstop);
      lines.push(`set tabstop=${basic.tabstop}`);
    }
    if (basic.shiftwidth) {
      lines.push(t.basicSettings.shiftwidth);
      lines.push(`set shiftwidth=${basic.shiftwidth}`);
    }
    if (basic.expandtab) {
      lines.push(t.basicSettings.expandtab);
      lines.push("set expandtab");
    }
    if (basic.autoindent) {
      lines.push(t.basicSettings.autoindent);
      lines.push("set autoindent");
    }
    if (basic.smartindent) {
      lines.push(t.basicSettings.smartindent);
      lines.push("set smartindent");
    }
    lines.push("");
  }

  // Search
  if (basic.hlsearch || basic.incsearch || basic.ignorecase || basic.smartcase) {
    lines.push(t.basicSettings.search);
    if (basic.hlsearch) {
      lines.push(t.basicSettings.hlsearch);
      lines.push("set hlsearch");
    }
    if (basic.incsearch) {
      lines.push(t.basicSettings.incsearch);
      lines.push("set incsearch");
    }
    if (basic.ignorecase) {
      lines.push(t.basicSettings.ignorecase);
      lines.push("set ignorecase");
    }
    if (basic.smartcase) {
      lines.push(t.basicSettings.smartcase);
      lines.push("set smartcase");
    }
    lines.push("");
  }

  // UI
  if (basic.showcmd || basic.showmode || basic.showmatch || basic.wildmenu) {
    lines.push(t.basicSettings.ui);
    if (basic.showcmd) {
      lines.push(t.basicSettings.showcmd);
      lines.push("set showcmd");
    }
    if (basic.showmode) {
      lines.push(t.basicSettings.showmode);
      lines.push("set showmode");
    }
    if (basic.showmatch) {
      lines.push(t.basicSettings.showmatch);
      lines.push("set showmatch");
    }
    if (basic.wildmenu) {
      lines.push(t.basicSettings.wildmenu);
      lines.push("set wildmenu");
    }
    lines.push("");
  }

  // Files
  if (!basic.backup || !basic.write || !basic.swapfile) {
    lines.push(t.basicSettings.files);
    if (!basic.backup) {
      lines.push(t.basicSettings.nobackup);
      lines.push("set nobackup");
    }
    if (!basic.write) {
      lines.push(t.basicSettings.nowrite);
      lines.push("set nowrite");
    }
    if (!basic.swapfile) {
      lines.push(t.basicSettings.noswapfile);
      lines.push("set noswapfile");
    }
    lines.push("");
  }

  // Collect all plugins and color schemes for vim-plug
  const enabledPluginIds = Object.entries(plugins)
    .filter(([, v]) => v === true)
    .map(([id]) => id);

  const hasPlugins = enabledPluginIds.length > 0;
  const hasColorScheme = COLOR_SCHEME_PLUGINS[theme.colorscheme] !== undefined;

  // vim-plug section
  if (hasPlugins || hasColorScheme) {
    lines.push(t.header.separator);
    lines.push(t.plugins.title);
    lines.push(t.header.separator);
    lines.push("");
    lines.push(t.plugins.step1);
    lines.push(t.plugins.step1Desc);
    lines.push('"\tcurl -fLo ~/.vim/autoload/plug.vim --create-dirs \\');
    lines.push('"\t  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim');
    lines.push("");
    lines.push("call plug#begin('~/.vim/plugged')");
    lines.push("");
    lines.push(t.plugins.colorSchemes);

    // Color scheme plugins
    if (hasColorScheme) {
      const colorSchemePlug = COLOR_SCHEME_PLUGINS[theme.colorscheme];
      if (theme.colorscheme === 'dracula') {
        lines.push(`  Plug '${colorSchemePlug}', { 'as': 'dracula' }`);
      } else {
        lines.push(`  Plug '${colorSchemePlug}'`);
      }
      lines.push("");
    }

    // Regular plugins
    if (enabledPluginIds.length > 0) {
      lines.push(t.plugins.plugins);
      enabledPluginIds.forEach((pluginId) => {
        const pluginInfo = PLUGINS.find((p) => p.id === pluginId);
        if (pluginInfo) {
          lines.push(`" ${pluginInfo.description}: ${pluginInfo.name}`);
          if (pluginInfo.branch) {
            lines.push(`  Plug '${pluginInfo.plug}', { 'branch': '${pluginInfo.branch}' }`);
          } else {
            lines.push(`  Plug '${pluginInfo.plug}'`);
          }
        } else {
          lines.push(`  Plug '${pluginId}'`);
        }
        const customConfig = plugins[`${pluginId}_config`];
        if (customConfig && typeof customConfig === 'string') {
          lines.push(`  ${t.plugins.customConfig} ${customConfig}`);
        }
      });
      lines.push("");
    }

    lines.push("call plug#end()");
    lines.push("");
    lines.push(t.plugins.step2);
    lines.push(t.plugins.step2Desc);
    lines.push("");
  }

  // Theme Settings (after plugins so color schemes are available)
  lines.push(t.header.separator);
  lines.push(t.theme.title);
  lines.push(t.header.separator);
  lines.push(`${t.theme.colorScheme} ${theme.colorscheme}`);
  lines.push(`colorscheme ${theme.colorscheme}`);
  lines.push(`${t.theme.background} ${theme.background}`);
  lines.push(`set background=${theme.background}`);
  lines.push("");

  return lines.join("\n");
}
